[package]
name = "git-history"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.19"
duckdb = "1.1"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
thiserror = "2.0"
chrono = "0.4"
